name: dart_tags
description: The library for work with music tags like ID3. Written on pure Dart. It can be used in flutter, web, and vm projects.
version: 0.2.2
homepage: https://github.com/NiKoTron/dart-tags
# author[s] is deprecated
# author: NiKoTron <nickolay.simonov@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0' 

dependencies:
  utf: ^0.9.0+5

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.4
